<template>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <table class="table table-striped table-dark">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Result</th>
                            <th scope="col">Checked</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>result</td>
                            <td>10</td>
                        </tr>
                    </tbody>
                </table>    
            </div>
        </div>
        <div class="row">
            <button>sss</button>
        </div>
    </div>
</template>


